type: objective
answers:
  '1':
    - C
    - 6
  '2':
    - D
    - 6
  '3':
    - B
    - 6
  '4':
    - B
    - 6
  '5':
    - C
    - 6
  '6':
    - C
    - 6
  '7':
    - C
    - 6
  '8':
    - C
    - 6
  '9':
    - A
    - 6
  '10':
    - B
    - 6
