type: objective
answers:
  '1':
    - C
    - 6
  '2':
    - B
    - 6
  '3':
    - D
    - 6
  '4':
    - B
    - 6
  '5':
    - D
    - 6
  '6':
    - C
    - 6
  '7':
    - - A
      - C
      - D
    - 12
  '8':
    - - A
      - C
    - 12
  '9':
    - - A
      - C
    - 12
  '10':
    - - B
      - C
    - 12
  '11':
    - - A
      - C
    - 12
  '12':
    - - A
      - C
      - D
    - 12
  '13':
    - B
    - 6
  '14':
    - C
    - 6
  '15':
    - - A
      - C
    - 12
  '16':
    - - A
      - D
    - 12
