type: objective
answers:
  '1':
    - B
    - 6
  '2':
    - A
    - 6
  '3':
    - B
    - 6
  '4':
    - A
    - 6
  '5':
    - A
    - 6
  '6':
    - A
    - 6
  '7':
    - B
    - 6
  '8':
    - A
    - 6
  '9':
    - B
    - 6
