type: objective
answers:
  '1':
    - D
    - 6
  '2':
    - C
    - 6
  '3':
    - D
    - 6
  '4':
    - D
    - 6
  '5':
    - D
    - 6
  '6':
    - C
    - 6
  '7':
    - B
    - 6
  '8':
    - B
    - 6
  '9':
    - A
    - 6
  '10':
    - C
    - 6
  '11':
    - B
    - 6
  '12':
    - C
    - 6
  '13':
    - A
    - 6
  '14':
    - A
    - 6
  '15':
    - C
    - 6
  '16':
    - B
    - 6
  '17':
    - B
    - 6
  '18':
    - D
    - 6
  '19':
    - B
    - 6
  '20':
    - D
    - 6
  '21':
    - A
    - 6
  '22':
    - D
    - 6
  '23':
    - C
    - 6
  '24':
    - A
    - 6
  '25':
    - B
    - 6
  '26':
    - B
    - 6
  '27':
    - B
    - 6
  '28':
    - D
    - 6
  '29':
    - A
    - 6
  '30':
    - C
    - 6
  '31':
    - D
    - 6
  '32':
    - A
    - 6
  '33':
    - B
    - 6
  '34':
    - B
    - 6
  '35':
    - C
    - 6
